<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="57297" started-at="2017-08-23T06:08:51Z" finished-at="2017-08-23T06:09:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="57297" started-at="2017-08-23T06:08:51Z" finished-at="2017-08-23T06:09:48Z">
      <class name="visscaa.Systeminqury">
        <test-method status="PASS" signature="beforeclass()[pri:0, instance:visscaa.Systeminqury@1d057a39]" name="beforeclass" is-config="true" duration-ms="11807" started-at="2017-08-23T14:08:51Z" finished-at="2017-08-23T14:09:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method status="PASS" signature="resident([Ljava.lang.String;)[pri:0, instance:visscaa.Systeminqury@1d057a39]" name="resident" duration-ms="39729" started-at="2017-08-23T14:09:02Z" data-provider="Systeminqury" finished-at="2017-08-23T14:09:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@23e84203]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resident -->
        <test-method status="FAIL" signature="resident([Ljava.lang.String;)[pri:0, instance:visscaa.Systeminqury@1d057a39]" name="resident" duration-ms="5740" started-at="2017-08-23T14:09:42Z" data-provider="Systeminqury" finished-at="2017-08-23T14:09:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@792b749c]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [新北市] but found [上海市]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [新北市] but found [上海市]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.demo.page.viss.residentinqury(viss.java:56)
	at visscaa.Systeminqury.resident(Systeminqury.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resident -->
      </class> <!-- visscaa.Systeminqury -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
